# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.16-SNAPSHOT


# Mod Properties
mod_version=1.1.2-mc26.2
maven_group=icu.takeneko
archives_base_name=startup_time

#Fabric api
fabric_api_version=0.159.0+26.2
